# fly.toml app configuration file generated for password-genie-wispy-flower-9704 on 2024-01-04T13:11:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "password-genie-wispy-flower-9704"
primary_region = "lax"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
